[package]
name = "subtle-codegen"
version = "0.1.1"
authors = ["Michael Rosenberg <micro@fastmail.com>"]

[dependencies]
quote = "0.3"
syn = "0.11"
subtle = "0.6"

[dev-dependencies]
compiletest_rs = "0.3"

[lib]
proc-macro = true
