[package]
name = "subtle-codegen"
version = "0.1.0"
authors = ["Michael Rosenberg <42micro@gmail.com>"]

[dependencies]
quote = "0.3"
syn = "0.11"

[dependencies.subtle]
git = "https://github.com/doomrobo/subtle.git"
branch = "ct-eq-everything"

[lib]
proc-macro = true
