[package]
name = "subtle-codegen"
version = "0.1.2"
authors = ["Michael Rosenberg <micro@fastmail.com>"]

[dependencies]
quote = "0.6"
proc-macro2 = "0.4"
syn = "0.14"
subtle = "0.6"

[dev-dependencies.compiletest_rs]
version = "0.3"
features = ["stable"]

[lib]
proc-macro = true
